[package]
name = "quasi"
version = "0.2.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A quasi-quoting macro system"
repository = "https://github.com/erickt/rust-quasi"
build = "build.rs"

[build-dependencies]
quasi_codegen = { version = "*", path = "quasi_codegen" }

[dev-dependencies]
aster = "*"
quasi_macros = { version = "*", path = "quasi_macros" }
syntex_syntax = "*"
