[package]
name = "quasi_tests"
version = "0.3.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A quasi-quoting macro system"
repository = "https://github.com/erickt/rust-quasi"
build = "build.rs"

[build-dependencies]
quasi_codegen = { version = "*", path = "../quasi_codegen", features = ["with-syntex"] }
syntex = { version = "*", path = "../../rust-syntex/syntex" }

[dev-dependencies]
aster = { version = "*", path = "../../rust-aster", features = ["with-syntex"] }
quasi = { version = "*", path = "../quasi", features = ["with-syntex"] }
syntex = { version = "*", path = "../../rust-syntex/syntex" }
syntex_syntax = { version = "*", path = "../../rust-syntex/syntex_syntax" }
