[package]
name = "quasi_macros"
version = "0.3.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A quasi-quoting macro system"
repository = "https://github.com/erickt/rust-quasi"

[lib]
name = "quasi_macros"
plugin = true

[dependencies]
quasi_codegen = { version = "*", path = "../quasi_codegen", default-features = false, features = ["nightly"] }

[dev-dependencies]
aster-syntax = { version = "*", path = "../../rust-aster/aster-syntax" }
quasi = { version = "*", path = "..", default-features = false, features = ["nightly"] }
